name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4.1.1
            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: crossbuild-essential-arm64 qemu-system-arm
                    version: 1.0

            -   name: Configure Project
                run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.type}} -DENABLE_CHECKS=ON

            -   name: Build Project
                run: make -j -C build VERBOSE=1

            # - name: Test Project
            #  runs: ctest --test-dir build
