name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   run: |
                    echo "deb mirror+file:/etc/apt/apt-mirrors.txt mantic main" | sudo tee /etc/apt/sources.list.d/temporary-repository.list
                    sudo apt update

            # -   uses: actions/checkout@v4.1.1
            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: gcc-13-aarch64-linux-gnu g++-13-aarch64-linux-gnu qemu-system-arm
                    version: 1.0

            -   name: aarch64-gcc version
                run: aarch64-linux-gnu-g++-13 --version -v

            # - name: Test Project
            #  runs: ctest --test-dir build
