name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Install aarch64-linux-gcc
                run: sudo apt search crossbuild-essential-arm64

            # - name: Test Project
            #  runs: ctest --test-dir build
