name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                packages: crossbuild-essential-arm64
                version: 1.0

            -   name: aarch64-gcc version
                run: aarch64-linux-gnu-g++ --version -v

            # - name: Test Project
            #  runs: ctest --test-dir build
