name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   run: cat /etc/apt/sources.list

            -   name: Install aarch64-gcc
                run: sudo apt search aarch64-linux-gnu

            # -   name: Install aarch64-gcc
            #     run: sudo apt install -y crossbuild-essential-arm64

            # -   name: aarch64-gcc version
            #     run: aarch64-linux-gnu-g++ --version -v

            # - name: Test Project
            #  runs: ctest --test-dir build
